### ISSUE TITLE
fix: Keplr cannot connect

### ISSUE THREAD

**Issue by fadeev** [tendermint/vue#243]
![unknown1](https://user-images.githubusercontent.com/332151/155301128-faf1b9f7-f7af-469a-ab76-8a30e6c0d764.png)

![unknown](https://user-images.githubusercontent.com/332151/155301145-6d138a51-8b17-4bff-8686-d82a9cae7f94.png)

![123123](https://user-images.githubusercontent.com/332151/155301159-3da4d17b-c424-4d90-9fa9-86cd403f431f.png)

![zxczc](https://user-images.githubusercontent.com/332151/155301168-86246fbb-6a8e-4050-97c6-0a911c38be25.png)

(from Discord)

**Comment by mihailmarcu** [comment]
@fadeev as mentioned in our meeting, I am coming with an update here:
— The scenarios that I was able to reproduce are the following: if we are trying to connect to the Keplr and there is not a single account in the wallet we get this error. We do not display the corresponding message that will help to understand what is the reason. I know that we have several scenarios when this error occurs, so we cannot solve it right away, since we need to foresee all possible scenarios when this error occurs.

Suggest keeping the issue open until we find all possible scenarios and then plan the refactoring.

**Comment by akarales** [comment]
connect when there is account, still get an error.

**Comment by akarales** [comment]
Found an issue connecting the kepl wallet. Seems like localhost should be a url perhaps. WebSocket connection to 'ws://localhost:26657/websocket' failed: 
(anonymous) @ vendor.71c4af46.js:83
vendor.71c4af46.js:83 Error: Client-js:WS Could not connect to websocket.
    at SPClient.onErrorWS (vendor.71c4af46.js:83:9904)
    at WebSocket._handleError (vendor.71c4af46.js:83:1430)
onErrorWS @ vendor.71c4af46.js:83
_handleError @ vendor.71c4af46.js:83
error (async)
e._addListeners @ vendor.71c4af46.js:83
(anonymous) @ vendor.71c4af46.js:83
Promise.then (async)
![error001](https://user-images.githubusercontent.com/169277/169634410-d9eb8dab-189c-4fe3-967f-ceb4ab244b6e.png)

**Comment by avenbreaks** [comment]
same problem eror connect using kepler 

![Screenshot_20220603_074450](https://user-images.githubusercontent.com/93043826/171763108-bd0b2fcf-1a18-4470-b8f8-3dfcab5b51bb.png)

**Comment by MariaPaypoint** [comment]
I have found a workaround to this problem (if it's cause is starting ignite not in localhost): it's need to set environment variables.

This is my example of yaml to start ignite in Kubernetes:
```
apiVersion: v1
kind: Pod
metadata:
  name: ignite-pod
  namespace: test
  labels:
    app.kubernetes.io/name: ignite-pod
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: ignite
      image: ignitehq/cli
      command: ['sleep', '172800']
      env:
        - name: VUE_APP_CUSTOM_URL
          value: "http://192.168.100.64:30018"
        - name: VUE_APP_API_COSMOS
          value: "http://192.168.100.64:30014"
        - name: VUE_APP_API_TENDERMINT
          value: "http://192.168.100.64:30010"
        - name: VUE_APP_WS_TENDERMINT
          value: "ws://192.168.100.64:30010/websocket"

---

apiVersion: v1
kind: Service
metadata:
  name: ignite-service
  namespace: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ignite-pod
  ports:
  
  - name: port-api-tendermint
    protocol: TCP
    port: 26657
    targetPort: 26657
    nodePort: 30010
    
  - name: port-api-cosmos
    protocol: TCP
    port: 1317
    targetPort: 1317
    nodePort: 30014
    
  - name: port-npm-run-dev
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30018
```

P.S. I found a hint here https://github.com/ignite/cli/commit/09edced5513445b635775b533701217a3e2126eb (probably later I will need to setup VITE_* env variables).
